accounts/urls.py
from django.urls import path, include

from .views import register

app_name = "accounts"
urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", register, name="register"),
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("learning_logs.urls")),
]

learning_logs/urls.py
from django.urls import path

from .views import (
    index,
    topics,
    topic,
    new_topic,
    new_entry,
    edit_entry,
    delete_entry,
    edit_topic,
    delete_topic,
)


app_name = "learning_logs"
urlpatterns = [
    path("", index, name="index"),
    path("new_topic/", new_topic, name="new_topic"),
    path("topics/", topics, name="topics"),
    path("topics/<int:topic_id>/", topic, name="topic"),
    path("topics/<int:topic_id>/new_entry/", new_entry, name="new_entry"),
    path("topics/<int:topic_id>/edit_topic/", edit_topic, name="edit_topic"),
    path("topics/<int:topic_id>/delete_topic/", delete_topic, name="delete_topic"),
    path("edit_entry/<int:entry_id>/", edit_entry, name="edit_entry"),
    path("delete_entry/<int:entry_id>/", delete_entry, name="delete_entry"),
]

accounts/models.py
from django.db import models

# Create your models here.

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about."""

    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic."""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        """Return a simple string representing the entry."""
        return f"{self.text[:50]}..." if len(self.text) > 50 else self.text

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text": ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Register a new user."""
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("accounts:login")

    context = {"form": form}
    return render(request, "registration/register.html", context)

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """The home page for Learning Log."""
    return render(request, "learning_logs/index.html")


@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by("-date_added")
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by("-date_added")
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/topic.html", context)


@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != "POST":
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect("learning_logs:topics")

    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)


@login_required
def edit_topic(request, topic_id):
    """Edit an existing topic."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != "POST":
        form = TopicForm(instance=topic)
    else:
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic.id)

    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/edit_topic.html", context)


@login_required
def delete_topic(request, topic_id):
    """Delete an existing entry."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method == "POST":
        topic.delete()
        return redirect("learning_logs:topics")
    context = {"topic": topic}
    return render(request, "learning_logs/delete_topic.html", context)


@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404

    if request.method != "POST":
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect("learning_logs:topic", topic_id)

    context = {"form": form, "topic": topic}
    return render(request, "learning_logs/new_entry.html", context)


@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method != "POST":
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("learning_logs:topic", topic.id)

    context = {"entry": entry, "topic": topic, "form": form}
    return render(request, "learning_logs/edit_entry.html", context)


@login_required
def delete_entry(request, entry_id):
    """Delete an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if topic.owner != request.user:
        raise Http404

    if request.method == "POST":
        entry.delete()
        return redirect("learning_logs:topic", topic.id)
    context = {"entry": entry, "topic": topic}
    return render(request, "learning_logs/delete_entry.html", context)

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Learning Logs</title>


    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <style>
        a{
            text-decoration: none;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <div class="container">
            <a href="{% url 'learning_logs:index' %}" class="navbar-brand">
                Learning Log
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul>

                <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <span class="navbar-text me-2">Hello, {{ user.username }}</span>
                        </li>
                    {% else %}
                        <li class="nav-item me-2">
                            <a href="{% url 'accounts:register' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'accounts:login' %}">Login</a>
                        </li>
                    {% endif %}
                </ul>
                
                {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button name="submit" class="btn btn-outline-secondary btn-sm">Log out</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </nav>

    <main class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>
</html>

learning_logs/templates/learning_logs/delete_entry.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <p>Delete entry: {{ entry.text }}</p>
    <form action="{% url 'learning_logs:delete_entry' entry.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/delete_topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <p>Delete topic: {{ topic.text }}</p>
    <form action="{% url 'learning_logs:delete_topic' topic.id %}" method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type='submit' content='Save changes' %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/edit_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <p>Edit topic:</p>
    <form action="{% url 'learning_logs:edit_topic' topic.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type='submit' content='Save changes' %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Track your learning</h1>

            <p class="lead">Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn something new about a topic, make an entry summarizing what you've learned.</p>

            <a href="{% url 'accounts:register' %}" class="btn btn-primary btn-lg mt-1">
                Register &raquo;
            </a>
        </div>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <p>Add new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type='submit' content='Add entry' %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
    <h2>Add a new topic</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% bootstrap_button button_type='submit' content='Add topic' %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1><a href="{% url 'learning_logs:topics' %}">{{ topic.text }}</a></h1>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>
    <div class="row">
        {% for entry in entries %}
            <div class="col-6">
                <div class="card mb-3">
                    <h4 class="card-header">
                        {{ entry.date_added|date:' H:i, M d Y' }}
                    </h4>
                    <div class="card-body">
                        {{ entry.text|linebreaks }}
                    </div>
                    <div class="card-footer text-center">
                        <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></small> &middot; 
                        <small><a href="{% url 'learning_logs:delete_entry' entry.id %}">Delete entry</a></small> 
                    </div>
                </div>
            </div>
        {% empty %}
            <p>No entries for this topic yet.</p>
        {% endfor %}
    </div>
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul class="list-group border-bottom pb-2 mb-4">
        {% for topic in topics %}
            <li class="list-group-item border-0">
                <a href="{% url 'learning_logs:topic' topic.id %}" class="lead">{{ topic.text }}</a> &middot; {{ topic.date_added|date:'M d, Y' }} &middot; 
                <a href="{% url 'learning_logs:edit_topic' topic.id %}">Edit topic</a> &middot; 
                <a href="{% url 'learning_logs:delete_topic' topic.id %}">Delete topic</a>
            </li>
        {% empty %}
            <li class="list-group-item border-0">No topics yet</li>
        {% endfor %}
    </ul>

    <a href="{% url 'learning_logs:new_topic' %}">Add new topic</a>
{% endblock content %}